name: Build Vue
on: [push]
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
    - uses: actions/checkout@v2
    - id: Build-Vue
      uses: gabuscuv/VuePagesAction@1.0.2c
      with:
        username: 'gabuscuv'
        reponame: '__gabuscuv.github.io'
        branch: 'gh-pages'
        token: ${{ secrets.GITHUB_TOKEN }}
